### ISSUE TITLE
1.4.3 didn't update the version in laps.php

### ISSUE THREAD

**Issue by kraftner** [Rarst/laps#10]
...so WP still shows 1.4.2. :disappointed: 

You probably need to release a 1.4.4 to fix this, right?

**Comment by Rarst** [comment]
Ugh, my bad. Need to automate this, WP readmes are silly to deal with in Composer–centric workflow.

**Comment by kraftner** [comment]
:smile: 

Shouldn't [this](https://github.com/Rarst/laps/blob/d2bece68e5c0035f06ecf42d97001f6e1a9689dc/RoboFile.php#L88) be doing it?

**Comment by Rarst** [comment]
It does, but it's not _automated_, I still need to call it. There should be some pre-tag hook in git or something, I should hook up version check/update on tag...

**Comment by kraftner** [comment]
Ah I see, well that is what human testers like me are good for.

**Comment by Rarst** [comment]
Apparently there is no git hook pre tag, because no one needs it. :\

Added a Robo task that wraps header update and Git tag into one operation for now.
