### ISSUE TITLE
Persistent profile storage

### ISSUE THREAD

**Issue by Rarst** [Rarst/laps#12]
While the primary design goals for the plugin were _immediate and visible_ feedback, that is of limited use in scenarios that don't have visibility or attention.

The logical enhancement would be ability to not just display but also collect profiles and display historical data in admin.

- [ ] profile format and storage
- [ ] collection contexts and settings
- [ ] admin UI for display

**Comment by Rarst** [comment]
Had been very uneager to work on this. I am just not responsible for any ongoing operation of WP sites in a way that _need_ this.

Thought about making this into a commercial version of the plugin. But:
- even free version is hardly used (relative to WP–scale)
- selling to developers is questionably wise
- selling products is still abysmal fit for me logistically (because Ukraine)

For now not giving up on the idea, but not a priority.

**Comment by danieliser** [comment]
@Rarst I could see this as highly useful as a replacement for P3 Profiler. That said I agree, not a lot of room for profit as the market probably consist of other plugin devs and agencies that deal with micro optimization.

**Comment by Rarst** [comment]
I am giving up now, it's a lot of work and I am no closer to confidence in commercial potential.
