### ISSUE TITLE
Make use of core query time start tracking

### ISSUE THREAD

**Issue by Rarst** [Rarst/laps#19]
WP 5.0 will start saving time start information for query data, see https://core.trac.wordpress.org/ticket/43315

Most importantly this enables being able to retroactively place early queries. Can also skip (and eventually drop) custom time start tracking.

**Comment by slaFFik** [comment]
@Rarst WordPress 5.0.1, to be exact.

**Comment by Rarst** [comment]
Don't depress me.

**Comment by slaFFik** [comment]
It's hard not to with WordPress.
