### ISSUE TITLE
I have the following error when trying to activate the plugin

### ISSUE THREAD

**Issue by slim16165** [Rarst/laps#22]
Uncaught Error: Class 'Rarst\Laps\Plugin' not found in wp-content/plugins/laps-master/laps.php:19 Stack trace: #0 public_html/wp-admin/includes/plugin.php(1897): include() #1 wp-admin/plugins.php(178): plugin_sandbox_scrape('laps-master/lap...') #2 {main} thrown in wp-content/plugins/laps-master/laps.php on line 19

**Comment by Rarst** [comment]
Which method did you use to install the plugin?

https://github.com/Rarst/laps#installation

**Comment by slim16165** [comment]
Thanks for the very fast answer.
I just downloaded the plugin and uploaded it to the plugin folder.
If you want to have a look I have a staging environment, I can provide you the login credentials.

**Comment by Rarst** [comment]
Define "downloaded" ? Did you get the built zip from releases section?

https://github.com/Rarst/laps/releases

**Comment by slim16165** [comment]
Mmm.. I don't remember, I fear I've made a mistake. I will try to download the stable release.

**Comment by slim16165** [comment]
You were right, thank you very much!
