### ISSUE TITLE
Installing Laps on a server makes it completely crash: HTTP ERROR 500

### ISSUE THREAD

**Issue by slim16165** [Rarst/laps#23]
I've downloaded the latest release, uploaded to WP and activated.

This appears to be the only error in the log: [Mon Nov 12 13:34:27.134313 2018] [proxy_fcgi:error] [pid `16779] [client 127.0.0.1:37620] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'GeoIp2\\Database\\Reader' not found in /wp-content/plugins/wordfence/models/common/wfGeoIP2.php:28\nStack trace:\n#0

/wp-content/plugins/wordfence/lib/wfUtils.php(1423): wfGeoIP2::shared()\n#1
 
/wp-content/plugins/wordfence/lib/wordfenceClass.php(1798): wfUtils::geoIPVersion()\n#2 

/wp-includes/class-wp-hook.php(286): wordfence::veryFirstAction('')\n#3 

/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)\n#4 

/wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#5 

/wp-settings.php(327): do_action('plugins_loaded')\n#6 

/wp-con...\n', referer: https://www.nonsolodiete.it/wp-admin/plugins.php?plugin_status=all&paged=1&s`

Disabling Wordfence 7.1.17 it works

**Comment by Rarst** [comment]
Duplicates #21
