### ISSUE TITLE
Redesign the UI

### ISSUE THREAD

**Issue by Rarst** [Rarst/laps#32]
Initial Laps UI was just put together from off the shelf Bootstrap components with minimal customization.

The parts that hadn't aged well:
- the look with multiple levels (much more likely now with automatic nesting)
- tooltips, which now tend to contain a lot more text (call trees, queries)

So basically all of it. :)

Tentative priorities:
- more cohesive looking timelines
- styled to render in arbitrary context, not just toolbar
- more appropriate and readable tooltip typography
- clearer title/description tooltip  sectioning, prominent display of elapsed time

I would guess this calls for a custom Tailwind build, rather than trying to wrangle Bootstrap further. Also re-evaluate tooltips script (the one used is from BS3, I think BS4 switched to external Popper.js since).

**Comment by Rarst** [comment]
I think this is not happening unless (1) I need to use the plugin a lot more myself again or (2) there is a path to commercial version.

Meanwhile closing as stale.

**Comment by lkraav** [comment]
> I think this is not happening unless (1) I need to use the plugin a lot more myself again

So what replaced Laps for you?

**Comment by Rarst** [comment]
It's not replaced by anything (because, biased opinion, there isn't anything better at what it does) but I have no personal WP sites left (things went static) and my performance work lately is more about shouting down front-end JS.
