### ISSUE TITLE
Expandable details on click of any section of the graph

### ISSUE THREAD

**Issue by danieliser** [Rarst/laps#36]
It would be nice to get a static scrollable overlay when you click any section of the graph.

Some hooks have so many items that you can't see them all via tooltips.

**Comment by Rarst** [comment]
Yeah, related to general pending UI redesign in #32 

The current implementation was put from off-the-shelf Bootstrap components and definitely at the point where it won't scale any further. :)

**Comment by Rarst** [comment]
Going to fold this into #32 since it's really not happening within current UI. :(
