### ISSUE TITLE
Typehint triggers fatal error on activation

### ISSUE THREAD

**Issue by davidnaviaweb** [Rarst/laps#39]
As said, with PHP 7.3.6, when activating the plugin it triggers the following error. I assume is due a bad type hinting:

`Fatal error: Uncaught TypeError: Argument 2 passed to Rarst\Laps\Formatter\Hook_Formatter::get_callback_name() must be of the type int, array given.
`

I'll try to send a pull request with the fix.
Regards.

**Comment by Rarst** [comment]
Huh. I am very interested how you end up with array in there. That... should not ever happen, but WordPress. :)

**Comment by davidnaviaweb** [comment]
Forget it. It is due the use of a very tweaky framework where the args array is very twisted. Thank you and good work!

**Comment by Rarst** [comment]
Gotcha. It must be doing something... interesting to mess with the argument count. :)
