### ISSUE TITLE
hybrid_get_prefix() is gone, crashes laps

### ISSUE THREAD

**Issue by lkraav** [Rarst/laps#4]
https://github.com/justintadlock/hybrid-core/commit/74318029457fda279de02e3d22d93e52e6a60d39

**Comment by Rarst** [comment]
Any idea what's the new approach for it? I will get it fixed with conditional, but probably won't tyr to rewrite handler for v3 right away if I have to take it apart for that... :)

**Comment by lkraav** [comment]
prefix is gone as a concept. I guess I would just if ( function_exists() ) it for backward compatibility?

**Comment by Rarst** [comment]
Are hooks gone too? So are Hybrid events in Laps will be useless altogether for hew version?

**Comment by lkraav** [comment]
yep, all done away with those.
