### ISSUE TITLE
What is "Query Setup"?

### ISSUE THREAD

**Issue by OpNop** [Rarst/laps#43]
I'm trying to debug where the slowdown is on our site and according to Laps, the largest time is spent on "Query Setup". According to Query Monitor, all the quires on the page are taking `0.5545` seconds, yet Query Setup is `1.397` seconds. 

![image](https://user-images.githubusercontent.com/14283547/76131704-c61d5680-5fcc-11ea-9444-6c1c7a8a7b8d.png)

Thanks

**Comment by Rarst** [comment]
Query Setup is everything that happens between the `wp_loaded` and `template_redirect` hooks, exclusive. So it's after core finished loading and until it's ready to start loading theme template. On top of my head it's usually just posts getting queried for main loop, but something else might be hooked around there.

The second bar seems to show you have some larger database query inside of it and red is likely network request. That should give you more details on what is slow. :)
