### ISSUE TITLE
Add "Requires PHP" to the readme.txt header

### ISSUE THREAD

**Issue by slaFFik** [Rarst/laps#45]
Because WP may start respecting that when activating plugins locally.

And right now the plugin crashes the site on PHP 5.6.

**Comment by Rarst** [comment]
How "may" are we talking about?

**Comment by slaFFik** [comment]
> How "may" are we talking about?

Unfortunately, I don't understand your question. Could you please elaborate?

**Comment by Rarst** [comment]
What is the practical value of having this (for non-official-repo plugin) at the moment, if any?

Are there hard plans to make use of it in core?

**Comment by slaFFik** [comment]
You provide a zip. User downloads a zip, unzips it into plugins directory. Opens Plugins admin area and activates the plugin.
Future versions of WP will not allow activating a plugin, if in its header there is an incompatible PHP version.
Core Trac:
- themes https://core.trac.wordpress.org/ticket/43992 (merged)
- plugins https://core.trac.wordpress.org/ticket/43992 (merged)

**Comment by Rarst** [comment]
Well, I don't _have_ a readme.txt :) However this is now (WP 5.8+) parsed out of plugin header instead, so added there.
