### ISSUE TITLE
Do not crash site on PHP < 7.1.3

### ISSUE THREAD

**Issue by slaFFik** [Rarst/laps#46]
Keep in sync `composer.json` and its `require.php` with a new additional `version_compare()` at the top of the `laps.php` file.

So basically, when the plugin is activated on PHP < 7.1 - do not crash the site, just do nothing.

**Comment by Rarst** [comment]
People don't read instructions and when it does nothing, I get to burn my time dealing with questions about it, no deal. :)

**Comment by slaFFik** [comment]
You don't have instructions about PHP version. And you provide an already built zip archive with all dependencies, so users don't need to install using composer.
So the issue is not in users :)

**Comment by slaFFik** [comment]
I don't mind you closing and ignoring that, but please be consistent.

If you provide a zip - assume users will actually use it. In that case, they don't see anywhere the PHP requirement. So it's a "good citizen" approach to not break sites by default when you provide artifacts and do not require people to build them themselves..

**Comment by Rarst** [comment]
Readme has the PHP requirement badge btw.

If I can think of smoother workflow that makes sense to me, I will consider it, but frankly 5-6 year old PHP versions are not a priority. If people choose to run something that old, it's on them to deal with.

**Comment by slaFFik** [comment]
Oh, right (about the badge). My internet is too poor today, so almost all images are not loading at all, so I missed that :) My bad (actually, triolan's).
Switched to mobile, now I see that.

Thanks for the explanation.
