### ISSUE TITLE
Не могу установить плагин на wp 5.5.1

### ISSUE THREAD

**Issue by tankist-web** [Rarst/laps#47]
Получаю
`Fatal error: Laps not fully installed! Please install with Composer or download full release archive. in /Users/viktor/web/wp-mohair-et-lama/wp-content/plugins/laps/laps.php on line 20`
Устанавливал через composer.
Спасибо

**Comment by Rarst** [comment]
Композером как `install` или `require` ?

Если `require` то включает ли проект общий сгенерированный `vendor/autoload.php` ?

**Comment by tankist-web** [comment]
Через `require`, как указано в `Installation`
Действительно, нужно было просто подключить `vendor/autoload.php`
Спасибо
