### ISSUE TITLE
Causing JSON error on staging using Gutenberg editor and ACF PRO

### ISSUE THREAD

**Issue by Foldfocus** [Rarst/laps#49]
We've been using laps in order to improve our PHP performance and spot performance issues. So far it had been working very good. But recently laps is causing our setup problems.

**Where?:**
We use the Gutenberg editor in combination with ACF PRO for our clients websites. In all Gutenberg editors we have on our staging. Locally works fine.

**What device?**
All devices, desktop + mobile.

**What browser?**
All browsers.

**What did you expect?**
1. Saving my current post and storing my changes into the database.
2. The loading button stops with the saving animation.
3. I get the `Page saved` message.

**What happend?**
Not what I expected. It varies randomly in three different responses. We couldn't spot a pattern why one of those results happend:
1. We get the error message `Updating failed. The response is not a valid JSON response.`
2. We get the error message `Updating failed.`
3. We stay infinitely in the "saving" process. When trying to leave the site, I get prompted that I have unsaved changes. When I try to open admin or the site during the saving process in a new tab, the site will stay blank and won't load. I need to close the tab in order to break the saving loop. Sometimes the changes have been saved, sometimes not. But I always have to close the saving browser tab.

![image](https://user-images.githubusercontent.com/40053632/102194032-1828cc00-3ebd-11eb-8d7c-fe32553eee51.png)
![image](https://user-images.githubusercontent.com/40053632/102194095-2d9df600-3ebd-11eb-8d2b-b9943bf30759.png)

**Comment by ramonfincken** [comment]
neat report, but try to open your developer tab to see the actual XHR/AJAX/json/rest responses to put them here as well

**Comment by Rarst** [comment]
Yeah, need to figure out what is going on with the response.

There is no general issue with Gutenberg/ACF that I know of, had used Laps with them myself.

**Comment by Rarst** [comment]
Closing, pending actionable info.
