### ISSUE TITLE
jQuery.isFunction() is deprecated

### ISSUE THREAD

**Issue by michaelbragg** [Rarst/laps#50]
With WordPress upgrading to jQuery 3. A number of functions have be deprecated.

The jQuery Migrate plugin is showing the Laps plugin has the following deprecated functions:

```js
jQuery.isFunction() is deprecated
```

From https://github.com/Rarst/laps/blob/master/public/js/laps.js#L54

Would you be open to hotfixing the Bootstap Tooltips plugin or updating it to a later compatable versions?

How to reproduce the issue:

1. Install WP 5.6
2. Install Laps (lastest)
3. Install [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper)
4. Tools > jQuery Migrate > jQuery Version: Default from WordPress
5. Tools > jQuery Migrate > Detect and log deprecations in the default WordPress version of jQuery: Check
6. Tools > jQuery Migrate > Log deprecations caused by anonymous users browsing your website: Check
7. Navigate pages on the site unsting the laps menu bar and hovering over a section to display the tool tip
8. Tools > jQuery Migrate > Logged deprecations

**Comment by Rarst** [comment]
This seems to still be present in latest v3 branch release of Bootstrap and v4 moved to Popper.js at the time so it's not just a matter of bumping minor v3 version.

According to jQuery docs this was deprecated _in_ jQuery 3.3, not _before v3_ it so to my understanding it will continue to work with v3 and won't be removed in that major version?

If so I would think this isn't worth messing with, would you concur? If the _breaking_ change to it was upcoming it would obviously be different, but it doesn't seem to be.

**Comment by michaelbragg** [comment]
I can understand your reluctance to mess with. Maybe something to consider moving forwards. 
Even dropping the plugins reliance on jQuery, if a suitable tooltip could be found?

**Comment by Rarst** [comment]
The whole thing is long overdue for new interface and revisiting dependency choices then.

I have no outstanding plans to work on that right now. I am pessimistic about introducing commercial version to fund it and it haven't been in my "fun" plans for a long while.

I still use the plugin and committed to maintenance, but minor deprecation is definitely not something I would revamp whole interface for. :)

Thank you for reporting! If any more like this pop-up that might make sense to address eventually.
