### ISSUE TITLE
What is inside Themes Load?

### ISSUE THREAD

**Issue by enniocecco** [Rarst/laps#51]
![themes-load](https://user-images.githubusercontent.com/5003225/114452313-9a5d9e80-9bd8-11eb-8a5b-1f38ed8b4208.png)

Hi, this data is loaded before rendering... how can i dig into that Themes loads to see what actually are those 30MB of data loaded?

Thanks

**Comment by Rarst** [comment]
Themes Load event covers load between `setup_theme` and `after_setup_theme` hooks, which would mostly be `functions.php` of parent/child themes (and translation/locale setup).

Unfortunately there is no way for Laps to get more more specific information about it automatically. You would need to poke through it manually or use a PHP-level profiler (xdebug or such).
