### ISSUE TITLE
upstream sent too big header while reading response header from upstream

### ISSUE THREAD

**Issue by erikdemarco** [Rarst/laps#52]
When I use nginx as a proxy to apache. Sometimes laps return response header too big because of the servertimings takes a lot of  response header.  How to turn off servertiming feature?

**Comment by Rarst** [comment]
Are you using the most current Laps version? From looking around I found typical value for proxies to allow for headers is 8KB, so Laps now trims its headers to about half that.

You can filter `laps_can_see` (boolean) to disable it, though checking for appropriate context since it controls visibility in general (so toolbar as well).

**Comment by erikdemarco** [comment]
@Rarst Nginx default value for proxy_buffer_size on ubuntu is only 4K.

How can I differentiate between each feature?
laps_can_see filter only have 1 param:  current_user_can( 'manage_options' ) 
apply_filters( 'laps_can_see', current_user_can( 'manage_options' ) )

**Comment by Rarst** [comment]
Up to general WordPress mechanics, `wp_doing_ajax()` and whatever it is for REST API if you are using it.

**Comment by erikdemarco** [comment]
@Rarst Im sorry. I'm still didnt get it.
What is the relation between wanting to disable servertiming and wp_doing_ajax()?

What i want to ask is it possible to disable servertiming with 'laps_can_see' as you suggest?

**Comment by Rarst** [comment]
Not tested
```php
add_filter( 'laps_can_see', function($input) {

if ( wp_doing_ajax() ) {
    return false;
}

return $input;
} );
```

**Comment by Rarst** [comment]
I've reduced hardcoded limit to 2K.

**Comment by iandunn** [comment]
I also ran into this with the 2k limit. Here's an example of working around that for specific URLs:

```php
/**
 * Disable laps when it breaks the request
 *
 * See https://github.com/Rarst/laps/issues/52
 */
add_filter( 'laps_can_see', function( $input ) {
	global $wp;

	$broken_urls = array(
		'wp-json/wordcamp-site-cloner/v1/sites'
	);

	if ( in_array( $wp->request, $broken_urls, true ) ) {
		$input = false;
	}

	return $input;
} );

```
