### ISSUE TITLE
How to install? Is this a module or plugin?

### ISSUE THREAD

**Issue by tronics** [Rarst/laps#53]
I am sorry but I do not understand how to **install** or **uninstall** this software.
- Do you put it inside wordpress folder and run composer?
- Is it a plugin (folder structure suggests not)?
- Is it a PHP module?

There should be 2 sentences giving some scope in the readme.

**Comment by Rarst** [comment]
Laps is a WordPress plugin and described as such in readme. I am not sure what about the folder structure gives you impression it's not.

As per [Installation](https://github.com/Rarst/laps#installation) in readme: the recommended way is to require it as part of full-site Composer stack, but there is also a ready-made zip archive provided that you can upload and use as any WP plugin.
