### ISSUE TITLE
PHP 8.x

### ISSUE THREAD

**Issue by zmonteca** [Rarst/laps#54]
Can we get this fixed so laps works with php 7.x & 8.x?

```
PHP 8.0.11 (cli) (built: Sep 23 2021 21:26:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.11, Copyright (c), by Zend Technologies
```

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rarst/laps[3.0, ..., 3.3.4] require php ^7.1.3 -> your php version (8.0.11) does not satisfy that requirement.
    - Root composer.json requires rarst/laps ^3.0 -> satisfiable by rarst/laps[3.0, ..., 3.3.4].
```

**Comment by Rarst** [comment]
I am not running PHP 8 locally yet, so I can't test right away is it possible to add it to compatible versions or code changes are required first.

Notably Laps itself doesn't enforce this, only Composer does.

If you could please try building with `--ignore-platform-req php` Composer flag and report if there are issues, that would be helpful to move this along. :)

**Comment by zmonteca** [comment]
@Rarst the ignore flag fixed it locally and laps installs perfectly fine and works perfectly fine as far as I can tell.

`composer clear-cache; composer install --ignore-platform-req=php; composer update --ignore-platform-req=php`

**Comment by zmonteca** [comment]
As an addition for anyone that this is affecting, there's a workaround in composer that I was not privy to. 

Given that Laps is PHP 8.0 compatible, I felt comfortable doing a platform override. 

Adding this to my composer worked perfectly.

```
    "config": {
        "platform": {
            "php": "7.4"
        }
    }
```

**Comment by zmonteca** [comment]
🙏
