### ISSUE TITLE
Option to push performance data to external analytics tools

### ISSUE THREAD

**Issue by lkraav** [Rarst/laps#6]
@Rarst is `laps` codebase prepared for hooking into measurement completion events and for example using  https://developers.google.com/analytics/devguides/collection/protocol/v1/ to post every item's measurement data?

**Comment by Rarst** [comment]
Making HTTP requests sounds like extremely good way to _kill_ performance, not measure it.

What would be the use case for it? Laps scope it lightweight runtime and easily accessible visuals. External services don't quite factor into that.

**Comment by lkraav** [comment]
Not if you queue the requests up and send in one bunch or something.

Use case? Measuring performance over time, detecting regression patterns, alerts. My particular trigger example would be that I'm testing the experimental `mod_h2` on apache, and it appears over time requests would simply stall for no reason for several seconds. Unless you manually inspect this across the team, you don't know whether it was network traffic delays by plugins, something messed up with transients causing repeated re-runs of update checks or a PHP, web-server level problem etc.

**Comment by Rarst** [comment]
I think you are looking at the wrong tool. For something like that you will be better served by tools capable of proper sampling, NewRelic or xhprof/etc. Much more information, much less impact on runtime.

**Comment by lkraav** [comment]
Well, with newrelic there's a major pricing difference.

Anyway, to make this really simple, if I could opt-in to a special action that gets fired and it would get all the measurement as an array in an argument, that would solve the problem and I could take it from there.

**Comment by Rarst** [comment]
You can access Stopwatch instance in `Laps::$stopwatch` after `admin_bar_menu:100`. This won't include SQL queries, since they need to use custom collection routine (WordPress!), but rest of captured data will be in it.

In a less hacky sense this sounds like more of a consideration for next major version, which isn't being actively worked on so far, see #3

**Comment by Rarst** [comment]
Way out of scope of current stable version so closing for now. :) Will keep in mind for future.

**Comment by lkraav** [comment]
I've also switched to johnbillion/query-monitor in the meanwhile.

**Comment by Rarst** [comment]
FYI v2 had shipped with unified event processing, so now it's trivial to get `$laps['records']` at the end of page load and do whatever you want with them. :)
